[package]
name = "clash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["client", "server"]

[dependencies]
bfbb = { git = "https://github.com/BfBBModdingTools/bfbb", branch = "main", features = ["serde"]}
tokio = { version = "1", features = ["rt", "rt-multi-thread", "io-util", "net", "macros"] }
serde = { version = "1", features = ["derive"] }
bytes = "1.1"
bincode = "1.3"
egui = "0.17"

thiserror = "1"
anyhow = "1"

log = "0.4"
